package tw.org.roadtoadventure.vo;
// Generated 2017/11/3 �W�� 02:21:29 by Hibernate Tools 5.2.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CodeTableId generated by hbm2java
 */
@Embeddable
public class CodeTableId implements java.io.Serializable {

	private String attributeName;
	private String code;
	private String value;

	public CodeTableId() {
	}

	public CodeTableId(String attributeName, String code, String value) {
		this.attributeName = attributeName;
		this.code = code;
		this.value = value;
	}

	@Column(name = "AttributeName", nullable = false, length = 50)
	public String getAttributeName() {
		return this.attributeName;
	}

	public void setAttributeName(String attributeName) {
		this.attributeName = attributeName;
	}

	@Column(name = "Code", nullable = false, length = 10)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "Value", nullable = false, length = 20)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CodeTableId))
			return false;
		CodeTableId castOther = (CodeTableId) other;

		return ((this.getAttributeName() == castOther.getAttributeName())
				|| (this.getAttributeName() != null && castOther.getAttributeName() != null
						&& this.getAttributeName().equals(castOther.getAttributeName())))
				&& ((this.getCode() == castOther.getCode()) || (this.getCode() != null && castOther.getCode() != null
						&& this.getCode().equals(castOther.getCode())))
				&& ((this.getValue() == castOther.getValue()) || (this.getValue() != null
						&& castOther.getValue() != null && this.getValue().equals(castOther.getValue())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getAttributeName() == null ? 0 : this.getAttributeName().hashCode());
		result = 37 * result + (getCode() == null ? 0 : this.getCode().hashCode());
		result = 37 * result + (getValue() == null ? 0 : this.getValue().hashCode());
		return result;
	}

}
