package tw.org.roadtoadventure.vo;
// Generated 2017/10/30 �U�� 10:59:10 by Hibernate Tools 5.2.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * CodeTable generated by hbm2java
 */
@Entity
@Table(name = "CodeTable", schema = "dbo", catalog = "RoadToAdventure")
public class CodeTable implements java.io.Serializable {

	private CodeTableId id;
	private String fattributeName;
	private String fcode;

	public CodeTable() {
	}

	public CodeTable(CodeTableId id) {
		this.id = id;
	}

	public CodeTable(CodeTableId id, String fattributeName, String fcode) {
		this.id = id;
		this.fattributeName = fattributeName;
		this.fcode = fcode;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "attributeName", column = @Column(name = "AttributeName", nullable = false, length = 50)),
			@AttributeOverride(name = "code", column = @Column(name = "Code", nullable = false, length = 10)),
			@AttributeOverride(name = "value", column = @Column(name = "Value", nullable = false, length = 20)) })
	public CodeTableId getId() {
		return this.id;
	}

	public void setId(CodeTableId id) {
		this.id = id;
	}

	@Column(name = "FAttributeName", length = 50)
	public String getFattributeName() {
		return this.fattributeName;
	}

	public void setFattributeName(String fattributeName) {
		this.fattributeName = fattributeName;
	}

	@Column(name = "FCode", length = 10)
	public String getFcode() {
		return this.fcode;
	}

	public void setFcode(String fcode) {
		this.fcode = fcode;
	}

}
