package tw.org.roadtoadventure.vo;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GroupJourneyDetail generated by hbm2java
 */
@Entity
@Table(name = "GroupJourneyDetail", schema = "dbo", catalog = "RoadToAdventure")
public class GroupJourneyDetail implements java.io.Serializable {

	private Integer groupJourneyDetailId;
	private GroupJourney groupJourney;
	private UserAccount userAccount;
	private Date createDate;
	private String location;

	public GroupJourneyDetail() {
	}


	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "GroupJourneyDetailID", unique = true, nullable = false)
	public Integer getGroupJourneyDetailId() {
		return this.groupJourneyDetailId;
	}

	public void setGroupJourneyDetailId(Integer groupJourneyDetailId) {
		this.groupJourneyDetailId = groupJourneyDetailId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "GroupJourneyID", nullable = false)
	public GroupJourney getGroupJourney() {
		return this.groupJourney;
	}

	public void setGroupJourney(GroupJourney groupJourney) {
		this.groupJourney = groupJourney;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CreateID", nullable = false)
	public UserAccount getUserAccount() {
		return this.userAccount;
	}

	public void setUserAccount(UserAccount userAccount) {
		this.userAccount = userAccount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreateDate", nullable = false, length = 23)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "Location", nullable = false, length = 50)
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

}
