package tw.org.roadtoadventure.vo;
// Generated 2017/11/3 �W�� 02:21:29 by Hibernate Tools 5.2.5.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GroupJourneyDetail generated by hbm2java
 */
@Entity
@Table(name = "GroupJourneyDetail", schema = "dbo", catalog = "RoadToAdventure")
public class GroupJourneyDetail implements java.io.Serializable {

	private GroupJourneyDetailId id;
	private GroupJourney groupJourney;
	private UserAccount userAccountByCreateId;
	private UserAccount userAccountByModifyId;
	private String latitude;
	private String longitude;
	private Date modifyDate;

	public GroupJourneyDetail() {
	}

	public GroupJourneyDetail(GroupJourneyDetailId id, GroupJourney groupJourney, UserAccount userAccountByCreateId,
			String latitude, String longitude) {
		this.id = id;
		this.groupJourney = groupJourney;
		this.userAccountByCreateId = userAccountByCreateId;
		this.latitude = latitude;
		this.longitude = longitude;
	}

	public GroupJourneyDetail(GroupJourneyDetailId id, GroupJourney groupJourney, UserAccount userAccountByCreateId,
			UserAccount userAccountByModifyId, String latitude, String longitude, Date modifyDate) {
		this.id = id;
		this.groupJourney = groupJourney;
		this.userAccountByCreateId = userAccountByCreateId;
		this.userAccountByModifyId = userAccountByModifyId;
		this.latitude = latitude;
		this.longitude = longitude;
		this.modifyDate = modifyDate;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "groupJourneyId", column = @Column(name = "GroupJourneyID", nullable = false)),
			@AttributeOverride(name = "groupId", column = @Column(name = "GroupID", nullable = false)),
			@AttributeOverride(name = "createDate", column = @Column(name = "CreateDate", nullable = false, length = 23)) })
	public GroupJourneyDetailId getId() {
		return this.id;
	}

	public void setId(GroupJourneyDetailId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "GroupJourneyID", referencedColumnName = "GroupJourneyID", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "GroupID", referencedColumnName = "GroupID", nullable = false, insertable = false, updatable = false) })
	public GroupJourney getGroupJourney() {
		return this.groupJourney;
	}

	public void setGroupJourney(GroupJourney groupJourney) {
		this.groupJourney = groupJourney;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CreateID", nullable = false)
	public UserAccount getUserAccountByCreateId() {
		return this.userAccountByCreateId;
	}

	public void setUserAccountByCreateId(UserAccount userAccountByCreateId) {
		this.userAccountByCreateId = userAccountByCreateId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ModifyID")
	public UserAccount getUserAccountByModifyId() {
		return this.userAccountByModifyId;
	}

	public void setUserAccountByModifyId(UserAccount userAccountByModifyId) {
		this.userAccountByModifyId = userAccountByModifyId;
	}

	@Column(name = "Latitude", nullable = false, length = 30)
	public String getLatitude() {
		return this.latitude;
	}

	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

	@Column(name = "Longitude", nullable = false, length = 30)
	public String getLongitude() {
		return this.longitude;
	}

	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ModifyDate", length = 23)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

}
