package tw.org.roadtoadventure.vo;
// Generated 2017/10/30 �U�� 10:59:10 by Hibernate Tools 5.2.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * GroupJourneyId generated by hbm2java
 */
@Embeddable
public class GroupJourneyId implements java.io.Serializable {

	private int groupJourneyId;
	private int groupId;

	public GroupJourneyId() {
	}

	public GroupJourneyId(int groupJourneyId, int groupId) {
		this.groupJourneyId = groupJourneyId;
		this.groupId = groupId;
	}

	@Column(name = "GroupJourneyID", nullable = false)
	public int getGroupJourneyId() {
		return this.groupJourneyId;
	}

	public void setGroupJourneyId(int groupJourneyId) {
		this.groupJourneyId = groupJourneyId;
	}

	@Column(name = "GroupID", nullable = false)
	public int getGroupId() {
		return this.groupId;
	}

	public void setGroupId(int groupId) {
		this.groupId = groupId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GroupJourneyId))
			return false;
		GroupJourneyId castOther = (GroupJourneyId) other;

		return (this.getGroupJourneyId() == castOther.getGroupJourneyId())
				&& (this.getGroupId() == castOther.getGroupId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getGroupJourneyId();
		result = 37 * result + this.getGroupId();
		return result;
	}

}
