package tw.org.roadtoadventure.vo;
// Generated 2017/10/30 �U�� 10:59:10 by Hibernate Tools 5.2.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * GroupChatId generated by hbm2java
 */
@Embeddable
public class GroupChatId implements java.io.Serializable {

	private int groupChatId;
	private int groupId;
	private String userId;

	public GroupChatId() {
	}

	public GroupChatId(int groupChatId, int groupId, String userId) {
		this.groupChatId = groupChatId;
		this.groupId = groupId;
		this.userId = userId;
	}

	@Column(name = "GroupChatID", nullable = false)
	public int getGroupChatId() {
		return this.groupChatId;
	}

	public void setGroupChatId(int groupChatId) {
		this.groupChatId = groupChatId;
	}

	@Column(name = "GroupID", nullable = false)
	public int getGroupId() {
		return this.groupId;
	}

	public void setGroupId(int groupId) {
		this.groupId = groupId;
	}

	@Column(name = "UserID", nullable = false, length = 20)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GroupChatId))
			return false;
		GroupChatId castOther = (GroupChatId) other;

		return (this.getGroupChatId() == castOther.getGroupChatId()) && (this.getGroupId() == castOther.getGroupId())
				&& ((this.getUserId() == castOther.getUserId()) || (this.getUserId() != null
						&& castOther.getUserId() != null && this.getUserId().equals(castOther.getUserId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getGroupChatId();
		result = 37 * result + this.getGroupId();
		result = 37 * result + (getUserId() == null ? 0 : this.getUserId().hashCode());
		return result;
	}

}
