package tw.org.roadtoadventure.vo;
// Generated 2017/11/3 �W�� 02:21:29 by Hibernate Tools 5.2.5.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GroupChat generated by hbm2java
 */
@Entity
@Table(name = "GroupChat", schema = "dbo", catalog = "RoadToAdventure")
public class GroupChat implements java.io.Serializable {

	private GroupChatId id;
	private UserInGroup userInGroup;
	private String content;
	private Date createDate;

	public GroupChat() {
	}

	public GroupChat(GroupChatId id, UserInGroup userInGroup, String content, Date createDate) {
		this.id = id;
		this.userInGroup = userInGroup;
		this.content = content;
		this.createDate = createDate;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "groupChatId", column = @Column(name = "GroupChatID", nullable = false)),
			@AttributeOverride(name = "groupId", column = @Column(name = "GroupID", nullable = false)),
			@AttributeOverride(name = "userId", column = @Column(name = "UserID", nullable = false, length = 20)) })
	public GroupChatId getId() {
		return this.id;
	}

	public void setId(GroupChatId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "UserID", referencedColumnName = "UserID", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "GroupID", referencedColumnName = "GroupID", nullable = false, insertable = false, updatable = false) })
	public UserInGroup getUserInGroup() {
		return this.userInGroup;
	}

	public void setUserInGroup(UserInGroup userInGroup) {
		this.userInGroup = userInGroup;
	}

	@Column(name = "content", nullable = false)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreateDate", nullable = false, length = 23)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
