package tw.org.roadtoadventure.vo;
// Generated 2017/11/3 �W�� 02:21:29 by Hibernate Tools 5.2.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * GroupRole generated by hbm2java
 */
@Entity
@Table(name = "GroupRole", schema = "dbo", catalog = "RoadToAdventure")
public class GroupRole implements java.io.Serializable {

	private String groupRoleId;
	private String groupRoleName;
	private Set<UserInGroup> userInGroups = new HashSet<UserInGroup>(0);
	private Set<Authority> authorities = new HashSet<Authority>(0);

	public GroupRole() {
	}

	public GroupRole(String groupRoleId, String groupRoleName) {
		this.groupRoleId = groupRoleId;
		this.groupRoleName = groupRoleName;
	}

	public GroupRole(String groupRoleId, String groupRoleName, Set<UserInGroup> userInGroups,
			Set<Authority> authorities) {
		this.groupRoleId = groupRoleId;
		this.groupRoleName = groupRoleName;
		this.userInGroups = userInGroups;
		this.authorities = authorities;
	}

	@Id

	@Column(name = "GroupRoleID", unique = true, nullable = false, length = 20)
	public String getGroupRoleId() {
		return this.groupRoleId;
	}

	public void setGroupRoleId(String groupRoleId) {
		this.groupRoleId = groupRoleId;
	}

	@Column(name = "GroupRoleName", nullable = false, length = 50)
	public String getGroupRoleName() {
		return this.groupRoleName;
	}

	public void setGroupRoleName(String groupRoleName) {
		this.groupRoleName = groupRoleName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "groupRole")
	public Set<UserInGroup> getUserInGroups() {
		return this.userInGroups;
	}

	public void setUserInGroups(Set<UserInGroup> userInGroups) {
		this.userInGroups = userInGroups;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "groupRoles")
	public Set<Authority> getAuthorities() {
		return this.authorities;
	}

	public void setAuthorities(Set<Authority> authorities) {
		this.authorities = authorities;
	}

}
