package tw.org.roadtoadventure.vo;
// Generated 2017/10/30 �U�� 10:59:10 by Hibernate Tools 5.2.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GroupJourney generated by hbm2java
 */
@Entity
@Table(name = "GroupJourney", schema = "dbo", catalog = "RoadToAdventure")
public class GroupJourney implements java.io.Serializable {

	private GroupJourneyId id;
	private Group group;
	private UserAccount userAccountByCreateId;
	private UserAccount userAccountByModifyId;
	private String groupJourneyName;
	private String groupJourneyContent;
	private Date createDate;
	private Date modifyTime;
	private Set<GroupJourneyDetail> groupJourneyDetails = new HashSet<GroupJourneyDetail>(0);

	public GroupJourney() {
	}

	public GroupJourney(GroupJourneyId id, Group group, UserAccount userAccountByCreateId, String groupJourneyName,
			Date createDate) {
		this.id = id;
		this.group = group;
		this.userAccountByCreateId = userAccountByCreateId;
		this.groupJourneyName = groupJourneyName;
		this.createDate = createDate;
	}

	public GroupJourney(GroupJourneyId id, Group group, UserAccount userAccountByCreateId,
			UserAccount userAccountByModifyId, String groupJourneyName, String groupJourneyContent, Date createDate,
			Date modifyTime, Set<GroupJourneyDetail> groupJourneyDetails) {
		this.id = id;
		this.group = group;
		this.userAccountByCreateId = userAccountByCreateId;
		this.userAccountByModifyId = userAccountByModifyId;
		this.groupJourneyName = groupJourneyName;
		this.groupJourneyContent = groupJourneyContent;
		this.createDate = createDate;
		this.modifyTime = modifyTime;
		this.groupJourneyDetails = groupJourneyDetails;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "groupJourneyId", column = @Column(name = "GroupJourneyID", nullable = false)),
			@AttributeOverride(name = "groupId", column = @Column(name = "GroupID", nullable = false)) })
	public GroupJourneyId getId() {
		return this.id;
	}

	public void setId(GroupJourneyId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "GroupID", nullable = false, insertable = false, updatable = false)
	public Group getGroup() {
		return this.group;
	}

	public void setGroup(Group group) {
		this.group = group;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CreateID", nullable = false)
	public UserAccount getUserAccountByCreateId() {
		return this.userAccountByCreateId;
	}

	public void setUserAccountByCreateId(UserAccount userAccountByCreateId) {
		this.userAccountByCreateId = userAccountByCreateId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ModifyID")
	public UserAccount getUserAccountByModifyId() {
		return this.userAccountByModifyId;
	}

	public void setUserAccountByModifyId(UserAccount userAccountByModifyId) {
		this.userAccountByModifyId = userAccountByModifyId;
	}

	@Column(name = "GroupJourneyName", nullable = false, length = 50)
	public String getGroupJourneyName() {
		return this.groupJourneyName;
	}

	public void setGroupJourneyName(String groupJourneyName) {
		this.groupJourneyName = groupJourneyName;
	}

	@Column(name = "GroupJourneyContent")
	public String getGroupJourneyContent() {
		return this.groupJourneyContent;
	}

	public void setGroupJourneyContent(String groupJourneyContent) {
		this.groupJourneyContent = groupJourneyContent;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreateDate", nullable = false, length = 23)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ModifyTime", length = 23)
	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "groupJourney")
	public Set<GroupJourneyDetail> getGroupJourneyDetails() {
		return this.groupJourneyDetails;
	}

	public void setGroupJourneyDetails(Set<GroupJourneyDetail> groupJourneyDetails) {
		this.groupJourneyDetails = groupJourneyDetails;
	}

}
