package tw.org.roadtoadventure.vo;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PersonalJourneyDetail generated by hbm2java
 */
@Entity
@Table(name = "PersonalJourneyDetail", schema = "dbo", catalog = "RoadToAdventure")
public class PersonalJourneyDetail implements java.io.Serializable {

	private Integer personalJourneyDetailId;
	private PersonalJourney personalJourney;
	private Date createDate;
	private String location;

	public PersonalJourneyDetail() {
	}

	public PersonalJourneyDetail(PersonalJourney personalJourney, String location) {
		this.personalJourney = personalJourney;
		this.location = location;
	}

	public PersonalJourneyDetail(PersonalJourney personalJourney, Date createDate, String location) {
		this.personalJourney = personalJourney;
		this.createDate = createDate;
		this.location = location;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "PersonalJourneyDetailID", unique = true, nullable = false)
	public Integer getPersonalJourneyDetailId() {
		return this.personalJourneyDetailId;
	}

	public void setPersonalJourneyDetailId(Integer personalJourneyDetailId) {
		this.personalJourneyDetailId = personalJourneyDetailId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PersonalJourneyID", nullable = false)
	public PersonalJourney getPersonalJourney() {
		return this.personalJourney;
	}

	public void setPersonalJourney(PersonalJourney personalJourney) {
		this.personalJourney = personalJourney;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreateDate", length = 23)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "Location", nullable = false, length = 50)
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

}