package tw.org.roadtoadventure.vo;
// Generated 2017/10/30 �U�� 10:59:10 by Hibernate Tools 5.2.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PersonalJourneyDetailId generated by hbm2java
 */
@Embeddable
public class PersonalJourneyDetailId implements java.io.Serializable {

	private int personalJourneyId;
	private String userId;
	private Date createDate;

	public PersonalJourneyDetailId() {
	}

	public PersonalJourneyDetailId(int personalJourneyId, String userId, Date createDate) {
		this.personalJourneyId = personalJourneyId;
		this.userId = userId;
		this.createDate = createDate;
	}

	@Column(name = "PersonalJourneyID", nullable = false)
	public int getPersonalJourneyId() {
		return this.personalJourneyId;
	}

	public void setPersonalJourneyId(int personalJourneyId) {
		this.personalJourneyId = personalJourneyId;
	}

	@Column(name = "UserID", nullable = false, length = 20)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "CreateDate", nullable = false, length = 23)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PersonalJourneyDetailId))
			return false;
		PersonalJourneyDetailId castOther = (PersonalJourneyDetailId) other;

		return (this.getPersonalJourneyId() == castOther.getPersonalJourneyId())
				&& ((this.getUserId() == castOther.getUserId()) || (this.getUserId() != null
						&& castOther.getUserId() != null && this.getUserId().equals(castOther.getUserId())))
				&& ((this.getCreateDate() == castOther.getCreateDate())
						|| (this.getCreateDate() != null && castOther.getCreateDate() != null
								&& this.getCreateDate().equals(castOther.getCreateDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPersonalJourneyId();
		result = 37 * result + (getUserId() == null ? 0 : this.getUserId().hashCode());
		result = 37 * result + (getCreateDate() == null ? 0 : this.getCreateDate().hashCode());
		return result;
	}

}
