package tw.org.roadtoadventure.vo;
// Generated 2017/10/30 �U�� 10:59:10 by Hibernate Tools 5.2.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PersonalJourney generated by hbm2java
 */
@Entity
@Table(name = "PersonalJourney", schema = "dbo", catalog = "RoadToAdventure")
public class PersonalJourney implements java.io.Serializable {

	private PersonalJourneyId id;
	private UserAccount userAccountByUserId;
	private UserAccount userAccountByCreateId;
	private String personalJourneyName;
	private String personalJourneyContent;
	private Date createDate;
	private String modifyId;
	private Date modifyDate;
	private Set<PersonalJourneyDetail> personalJourneyDetails = new HashSet<PersonalJourneyDetail>(0);

	public PersonalJourney() {
	}

	public PersonalJourney(PersonalJourneyId id, UserAccount userAccountByUserId, UserAccount userAccountByCreateId,
			String personalJourneyName, Date createDate) {
		this.id = id;
		this.userAccountByUserId = userAccountByUserId;
		this.userAccountByCreateId = userAccountByCreateId;
		this.personalJourneyName = personalJourneyName;
		this.createDate = createDate;
	}

	public PersonalJourney(PersonalJourneyId id, UserAccount userAccountByUserId, UserAccount userAccountByCreateId,
			String personalJourneyName, String personalJourneyContent, Date createDate, String modifyId,
			Date modifyDate, Set<PersonalJourneyDetail> personalJourneyDetails) {
		this.id = id;
		this.userAccountByUserId = userAccountByUserId;
		this.userAccountByCreateId = userAccountByCreateId;
		this.personalJourneyName = personalJourneyName;
		this.personalJourneyContent = personalJourneyContent;
		this.createDate = createDate;
		this.modifyId = modifyId;
		this.modifyDate = modifyDate;
		this.personalJourneyDetails = personalJourneyDetails;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "personalJourneyId", column = @Column(name = "PersonalJourneyID", nullable = false)),
			@AttributeOverride(name = "userId", column = @Column(name = "UserID", nullable = false, length = 20)) })
	public PersonalJourneyId getId() {
		return this.id;
	}

	public void setId(PersonalJourneyId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UserID", nullable = false, insertable = false, updatable = false)
	public UserAccount getUserAccountByUserId() {
		return this.userAccountByUserId;
	}

	public void setUserAccountByUserId(UserAccount userAccountByUserId) {
		this.userAccountByUserId = userAccountByUserId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CreateID", nullable = false)
	public UserAccount getUserAccountByCreateId() {
		return this.userAccountByCreateId;
	}

	public void setUserAccountByCreateId(UserAccount userAccountByCreateId) {
		this.userAccountByCreateId = userAccountByCreateId;
	}

	@Column(name = "PersonalJourneyName", nullable = false, length = 50)
	public String getPersonalJourneyName() {
		return this.personalJourneyName;
	}

	public void setPersonalJourneyName(String personalJourneyName) {
		this.personalJourneyName = personalJourneyName;
	}

	@Column(name = "PersonalJourneyContent")
	public String getPersonalJourneyContent() {
		return this.personalJourneyContent;
	}

	public void setPersonalJourneyContent(String personalJourneyContent) {
		this.personalJourneyContent = personalJourneyContent;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreateDate", nullable = false, length = 23)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "ModifyID", length = 20)
	public String getModifyId() {
		return this.modifyId;
	}

	public void setModifyId(String modifyId) {
		this.modifyId = modifyId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ModifyDate", length = 23)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personalJourney")
	public Set<PersonalJourneyDetail> getPersonalJourneyDetails() {
		return this.personalJourneyDetails;
	}

	public void setPersonalJourneyDetails(Set<PersonalJourneyDetail> personalJourneyDetails) {
		this.personalJourneyDetails = personalJourneyDetails;
	}

}
