package tw.org.roadtoadventure.vo;
// Generated 2017/11/3 �W�� 02:21:29 by Hibernate Tools 5.2.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PersonalJourney generated by hbm2java
 */
@Entity
@Table(name = "PersonalJourney", schema = "dbo", catalog = "RoadToAdventure")
public class PersonalJourney implements java.io.Serializable {

	private Integer personalJourneyId;
	private UserAccount userAccountByModifyId;
	private UserAccount userAccountByCreateId;
	private String personalJourneyName;
	private String personalJourneyContent;
	private Date createDate;
	private Date modifyDate;
	private String overviewPolyline;
	private Date beginDate;
	private Date endDate;
	private char status;
	private Set<PersonalJourneyDetail> personalJourneyDetails = new HashSet<PersonalJourneyDetail>(0);

	public PersonalJourney() {
	}

	public PersonalJourney(UserAccount userAccountByCreateId, String personalJourneyName, Date createDate) {
		this.userAccountByCreateId = userAccountByCreateId;
		this.personalJourneyName = personalJourneyName;
		this.createDate = createDate;
	}

	public PersonalJourney(UserAccount userAccountByModifyId, UserAccount userAccountByCreateId,
			String personalJourneyName, String personalJourneyContent, Date createDate, Date modifyDate,
			String overviewPolyline, Set<PersonalJourneyDetail> personalJourneyDetails) {
		this.userAccountByModifyId = userAccountByModifyId;
		this.userAccountByCreateId = userAccountByCreateId;
		this.personalJourneyName = personalJourneyName;
		this.personalJourneyContent = personalJourneyContent;
		this.createDate = createDate;
		this.modifyDate = modifyDate;
		this.overviewPolyline = overviewPolyline;
		this.personalJourneyDetails = personalJourneyDetails;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "PersonalJourneyID", unique = true, nullable = false)
	public Integer getPersonalJourneyId() {
		return this.personalJourneyId;
	}

	public void setPersonalJourneyId(Integer personalJourneyId) {
		this.personalJourneyId = personalJourneyId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ModifyID")
	public UserAccount getUserAccountByModifyId() {
		return this.userAccountByModifyId;
	}

	public void setUserAccountByModifyId(UserAccount userAccountByModifyId) {
		this.userAccountByModifyId = userAccountByModifyId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CreateID", nullable = false)
	public UserAccount getUserAccountByCreateId() {
		return this.userAccountByCreateId;
	}

	public void setUserAccountByCreateId(UserAccount userAccountByCreateId) {
		this.userAccountByCreateId = userAccountByCreateId;
	}

	@Column(name = "PersonalJourneyName", nullable = false, length = 50)
	public String getPersonalJourneyName() {
		return this.personalJourneyName;
	}

	public void setPersonalJourneyName(String personalJourneyName) {
		this.personalJourneyName = personalJourneyName;
	}

	@Column(name = "PersonalJourneyContent")
	public String getPersonalJourneyContent() {
		return this.personalJourneyContent;
	}

	public void setPersonalJourneyContent(String personalJourneyContent) {
		this.personalJourneyContent = personalJourneyContent;
	}
	@Column(name = "Status", nullable = false, length = 1)
	public char getStatus() {
		return status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreateDate", nullable = false, length = 23)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ModifyDate", length = 23)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	@Column(name = "OverviewPolyline")
	public String getOverviewPolyline() {
		return this.overviewPolyline;
	}

	public void setOverviewPolyline(String overviewPolyline) {
		this.overviewPolyline = overviewPolyline;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personalJourney")
	public Set<PersonalJourneyDetail> getPersonalJourneyDetails() {
		return this.personalJourneyDetails;
	}

	public void setPersonalJourneyDetails(Set<PersonalJourneyDetail> personalJourneyDetails) {
		this.personalJourneyDetails = personalJourneyDetails;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "BeginDate", length = 23)
	public Date getBeginDate() {
		return beginDate;
	}

	public void setBeginDate(Date beginDate) {
		this.beginDate = beginDate;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EndDate", length = 23)
	public Date getEndDate() {
		return endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

}
