package tw.org.roadtoadventure.vo;
// Generated 2017/10/30 �U�� 10:59:10 by Hibernate Tools 5.2.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PersonalJourneyId generated by hbm2java
 */
@Embeddable
public class PersonalJourneyId implements java.io.Serializable {

	private int personalJourneyId;
	private String userId;

	public PersonalJourneyId() {
	}

	public PersonalJourneyId(int personalJourneyId, String userId) {
		this.personalJourneyId = personalJourneyId;
		this.userId = userId;
	}

	@Column(name = "PersonalJourneyID", nullable = false)
	public int getPersonalJourneyId() {
		return this.personalJourneyId;
	}

	public void setPersonalJourneyId(int personalJourneyId) {
		this.personalJourneyId = personalJourneyId;
	}

	@Column(name = "UserID", nullable = false, length = 20)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PersonalJourneyId))
			return false;
		PersonalJourneyId castOther = (PersonalJourneyId) other;

		return (this.getPersonalJourneyId() == castOther.getPersonalJourneyId())
				&& ((this.getUserId() == castOther.getUserId()) || (this.getUserId() != null
						&& castOther.getUserId() != null && this.getUserId().equals(castOther.getUserId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPersonalJourneyId();
		result = 37 * result + (getUserId() == null ? 0 : this.getUserId().hashCode());
		return result;
	}

}
