package tw.org.roadtoadventure.vo;
// Generated 2017/10/30 �U�� 10:59:10 by Hibernate Tools 5.2.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * UserRole generated by hbm2java
 */
@Entity
@Table(name = "UserRole", schema = "dbo", catalog = "RoadToAdventure")
public class UserRole implements java.io.Serializable {

	private String userRoleId;
	private String userRoleName;
	private Set<Authority> authorities = new HashSet<Authority>(0);

	public UserRole() {
	}

	public UserRole(String userRoleId, String userRoleName) {
		this.userRoleId = userRoleId;
		this.userRoleName = userRoleName;
	}

	public UserRole(String userRoleId, String userRoleName, Set<Authority> authorities) {
		this.userRoleId = userRoleId;
		this.userRoleName = userRoleName;
		this.authorities = authorities;
	}

	@Id

	@Column(name = "UserRoleID", unique = true, nullable = false, length = 20)
	public String getUserRoleId() {
		return this.userRoleId;
	}

	public void setUserRoleId(String userRoleId) {
		this.userRoleId = userRoleId;
	}

	@Column(name = "UserRoleName", nullable = false, length = 50)
	public String getUserRoleName() {
		return this.userRoleName;
	}

	public void setUserRoleName(String userRoleName) {
		this.userRoleName = userRoleName;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "userRoles")
	public Set<Authority> getAuthorities() {
		return this.authorities;
	}

	public void setAuthorities(Set<Authority> authorities) {
		this.authorities = authorities;
	}

}
