package tw.org.roadtoadventure.vo;
// Generated 2017/11/3 �W�� 02:21:29 by Hibernate Tools 5.2.5.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserFriend generated by hbm2java
 */
@Entity
@Table(name = "UserFriend", schema = "dbo", catalog = "RoadToAdventure")
public class UserFriend implements java.io.Serializable {

	private UserFriendId id;
	private Date createDate;

	public UserFriend() {
	}

	public UserFriend(UserFriendId id, Date createDate) {
		this.id = id;
		this.createDate = createDate;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "userId", column = @Column(name = "UserID", nullable = false, length = 20)),
			@AttributeOverride(name = "friendId", column = @Column(name = "FriendID", nullable = false, length = 20)) })
	public UserFriendId getId() {
		return this.id;
	}

	public void setId(UserFriendId id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreateDate", nullable = false, length = 23)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
