package tw.org.roadtoadventure.vo;
// Generated 2017/10/30 �U�� 10:59:10 by Hibernate Tools 5.2.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserAccount generated by hbm2java
 */
@Entity
@Table(name = "UserAccount", schema = "dbo", catalog = "RoadToAdventure")
public class UserAccount implements java.io.Serializable {

	private String userId;
	private String userName;
	private String userPicture;
	private String userRoleId;
	private String email;
	private String password;
	private String lastPassword;
	private Date lastLoginTime;
	private Character isEnabled;
	private Character isVerification;
	private String createId;
	private Date createDate;
	private String modifyId;
	private Date modifyDate;
	private Set<PersonalJourney> personalJourneysForUserId = new HashSet<PersonalJourney>(0);
	private Set<PersonalJourney> personalJourneysForCreateId = new HashSet<PersonalJourney>(0);
	private Set<GroupJourneyDetail> groupJourneyDetailsForCreateId = new HashSet<GroupJourneyDetail>(0);
	private Set<GroupJourneyDetail> groupJourneyDetailsForModifyId = new HashSet<GroupJourneyDetail>(0);
	private Set<Group> groupsForCreateId = new HashSet<Group>(0);
	private Set<UserInGroup> userInGroups = new HashSet<UserInGroup>(0);
	private Set<Group> groupsForModifyId = new HashSet<Group>(0);
	private Set<GroupJourney> groupJourneysForCreateId = new HashSet<GroupJourney>(0);
	private Set<GroupJourney> groupJourneysForModifyId = new HashSet<GroupJourney>(0);
	private Set<PersonalJourney> personalJourneysForUserId_1 = new HashSet<PersonalJourney>(0);

	public UserAccount() {
	}

	public UserAccount(String userId, String userName, String userRoleId, String email, String password,
			String createId, Date createDate) {
		this.userId = userId;
		this.userName = userName;
		this.userRoleId = userRoleId;
		this.email = email;
		this.password = password;
		this.createId = createId;
		this.createDate = createDate;
	}

	public UserAccount(String userId, String userName, String userPicture, String userRoleId, String email,
			String password, String lastPassword, Date lastLoginTime, Character isEnabled, Character isVerification,
			String createId, Date createDate, String modifyId, Date modifyDate,
			Set<PersonalJourney> personalJourneysForUserId, Set<PersonalJourney> personalJourneysForCreateId,
			Set<GroupJourneyDetail> groupJourneyDetailsForCreateId,
			Set<GroupJourneyDetail> groupJourneyDetailsForModifyId, Set<Group> groupsForCreateId,
			Set<UserInGroup> userInGroups, Set<Group> groupsForModifyId, Set<GroupJourney> groupJourneysForCreateId,
			Set<GroupJourney> groupJourneysForModifyId, Set<PersonalJourney> personalJourneysForUserId_1) {
		this.userId = userId;
		this.userName = userName;
		this.userPicture = userPicture;
		this.userRoleId = userRoleId;
		this.email = email;
		this.password = password;
		this.lastPassword = lastPassword;
		this.lastLoginTime = lastLoginTime;
		this.isEnabled = isEnabled;
		this.isVerification = isVerification;
		this.createId = createId;
		this.createDate = createDate;
		this.modifyId = modifyId;
		this.modifyDate = modifyDate;
		this.personalJourneysForUserId = personalJourneysForUserId;
		this.personalJourneysForCreateId = personalJourneysForCreateId;
		this.groupJourneyDetailsForCreateId = groupJourneyDetailsForCreateId;
		this.groupJourneyDetailsForModifyId = groupJourneyDetailsForModifyId;
		this.groupsForCreateId = groupsForCreateId;
		this.userInGroups = userInGroups;
		this.groupsForModifyId = groupsForModifyId;
		this.groupJourneysForCreateId = groupJourneysForCreateId;
		this.groupJourneysForModifyId = groupJourneysForModifyId;
		this.personalJourneysForUserId_1 = personalJourneysForUserId_1;
	}

	@Id

	@Column(name = "UserID", unique = true, nullable = false, length = 20)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "UserName", nullable = false, length = 50)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "UserPicture")
	public String getUserPicture() {
		return this.userPicture;
	}

	public void setUserPicture(String userPicture) {
		this.userPicture = userPicture;
	}

	@Column(name = "UserRoleID", nullable = false, length = 20)
	public String getUserRoleId() {
		return this.userRoleId;
	}

	public void setUserRoleId(String userRoleId) {
		this.userRoleId = userRoleId;
	}

	@Column(name = "Email", nullable = false, length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "Password", nullable = false, length = 32)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "LastPassword", length = 32)
	public String getLastPassword() {
		return this.lastPassword;
	}

	public void setLastPassword(String lastPassword) {
		this.lastPassword = lastPassword;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LastLoginTime", length = 23)
	public Date getLastLoginTime() {
		return this.lastLoginTime;
	}

	public void setLastLoginTime(Date lastLoginTime) {
		this.lastLoginTime = lastLoginTime;
	}

	@Column(name = "IsEnabled", length = 1)
	public Character getIsEnabled() {
		return this.isEnabled;
	}

	public void setIsEnabled(Character isEnabled) {
		this.isEnabled = isEnabled;
	}

	@Column(name = "IsVerification", length = 1)
	public Character getIsVerification() {
		return this.isVerification;
	}

	public void setIsVerification(Character isVerification) {
		this.isVerification = isVerification;
	}

	@Column(name = "CreateID", nullable = false, length = 20)
	public String getCreateId() {
		return this.createId;
	}

	public void setCreateId(String createId) {
		this.createId = createId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreateDate", nullable = false, length = 23)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "ModifyID", length = 20)
	public String getModifyId() {
		return this.modifyId;
	}

	public void setModifyId(String modifyId) {
		this.modifyId = modifyId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ModifyDate", length = 23)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userAccountByUserId")
	public Set<PersonalJourney> getPersonalJourneysForUserId() {
		return this.personalJourneysForUserId;
	}

	public void setPersonalJourneysForUserId(Set<PersonalJourney> personalJourneysForUserId) {
		this.personalJourneysForUserId = personalJourneysForUserId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userAccountByCreateId")
	public Set<PersonalJourney> getPersonalJourneysForCreateId() {
		return this.personalJourneysForCreateId;
	}

	public void setPersonalJourneysForCreateId(Set<PersonalJourney> personalJourneysForCreateId) {
		this.personalJourneysForCreateId = personalJourneysForCreateId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userAccountByCreateId")
	public Set<GroupJourneyDetail> getGroupJourneyDetailsForCreateId() {
		return this.groupJourneyDetailsForCreateId;
	}

	public void setGroupJourneyDetailsForCreateId(Set<GroupJourneyDetail> groupJourneyDetailsForCreateId) {
		this.groupJourneyDetailsForCreateId = groupJourneyDetailsForCreateId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userAccountByModifyId")
	public Set<GroupJourneyDetail> getGroupJourneyDetailsForModifyId() {
		return this.groupJourneyDetailsForModifyId;
	}

	public void setGroupJourneyDetailsForModifyId(Set<GroupJourneyDetail> groupJourneyDetailsForModifyId) {
		this.groupJourneyDetailsForModifyId = groupJourneyDetailsForModifyId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userAccountByCreateId")
	public Set<Group> getGroupsForCreateId() {
		return this.groupsForCreateId;
	}

	public void setGroupsForCreateId(Set<Group> groupsForCreateId) {
		this.groupsForCreateId = groupsForCreateId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userAccount")
	public Set<UserInGroup> getUserInGroups() {
		return this.userInGroups;
	}

	public void setUserInGroups(Set<UserInGroup> userInGroups) {
		this.userInGroups = userInGroups;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userAccountByModifyId")
	public Set<Group> getGroupsForModifyId() {
		return this.groupsForModifyId;
	}

	public void setGroupsForModifyId(Set<Group> groupsForModifyId) {
		this.groupsForModifyId = groupsForModifyId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userAccountByCreateId")
	public Set<GroupJourney> getGroupJourneysForCreateId() {
		return this.groupJourneysForCreateId;
	}

	public void setGroupJourneysForCreateId(Set<GroupJourney> groupJourneysForCreateId) {
		this.groupJourneysForCreateId = groupJourneysForCreateId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userAccountByModifyId")
	public Set<GroupJourney> getGroupJourneysForModifyId() {
		return this.groupJourneysForModifyId;
	}

	public void setGroupJourneysForModifyId(Set<GroupJourney> groupJourneysForModifyId) {
		this.groupJourneysForModifyId = groupJourneysForModifyId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userAccountByUserId")
	public Set<PersonalJourney> getPersonalJourneysForUserId_1() {
		return this.personalJourneysForUserId_1;
	}

	public void setPersonalJourneysForUserId_1(Set<PersonalJourney> personalJourneysForUserId_1) {
		this.personalJourneysForUserId_1 = personalJourneysForUserId_1;
	}

}
