package tw.org.roadtoadventure.vo;
// Generated 2017/10/30 �U�� 10:59:10 by Hibernate Tools 5.2.5.Final

import java.util.Collection;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;

/**
 * UserAccount generated by hbm2java
 */
@Entity
@Table(name = "UserAccount", schema = "dbo", catalog = "RoadToAdventure")
public class UserAccount implements java.io.Serializable ,UserDetails {

	private String userId;
	private String userName;
	private String userPicture;
	private String userRoleId;
	private String email;
	private String password;
	private String lastPassword;
	private Date lastLoginTime;
	private Character isEnabled;
	private Character isVerification;
	private String createId;
	private Date createDate;
	private String modifyId;
	private Date modifyDate;
	private Set<PersonalJourney> personalJourneysForUserId = new HashSet<PersonalJourney>(0);
	private Set<PersonalJourney> personalJourneysForCreateId = new HashSet<PersonalJourney>(0);
	private Set<GroupJourneyDetail> groupJourneyDetails = new HashSet<GroupJourneyDetail>(0);
	private Set<Group> groupsForCreateId = new HashSet<Group>(0);
	private Set<UserInGroup> userInGroups = new HashSet<UserInGroup>(0);
	private Set<Group> groupsForModifyId = new HashSet<Group>(0);
	private Set<GroupJourney> groupJourneysForCreateId = new HashSet<GroupJourney>(0);
	private Set<GroupJourney> groupJourneysForModifyId = new HashSet<GroupJourney>(0);
	private Set<PersonalJourney> personalJourneysForUserId_1 = new HashSet<PersonalJourney>(0);

	public UserAccount() {
	}


	@Id

	@Column(name = "UserID", unique = true, nullable = false, length = 20)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "UserName", nullable = false, length = 50)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "UserPicture")
	public String getUserPicture() {
		return this.userPicture;
	}

	public void setUserPicture(String userPicture) {
		this.userPicture = userPicture;
	}

	@Column(name = "UserRoleID", nullable = false, length = 20)
	public String getUserRoleId() {
		return this.userRoleId;
	}

	public void setUserRoleId(String userRoleId) {
		this.userRoleId = userRoleId;
	}

	@Column(name = "Email", nullable = false, length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "Password", nullable = false, length = 64)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "LastPassword", length = 64)
	public String getLastPassword() {
		return this.lastPassword;
	}

	public void setLastPassword(String lastPassword) {
		this.lastPassword = lastPassword;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LastLoginTime", length = 23)
	public Date getLastLoginTime() {
		return this.lastLoginTime;
	}

	public void setLastLoginTime(Date lastLoginTime) {
		this.lastLoginTime = lastLoginTime;
	}

	@Column(name = "IsEnabled", length = 1)
	public Character getIsEnabled() {
		return this.isEnabled;
	}

	public void setIsEnabled(Character isEnabled) {
		this.isEnabled = isEnabled;
	}

	@Column(name = "IsVerification", length = 1)
	public Character getIsVerification() {
		return this.isVerification;
	}

	public void setIsVerification(Character isVerification) {
		this.isVerification = isVerification;
	}

	@Column(name = "CreateID", nullable = false, length = 20)
	public String getCreateId() {
		return this.createId;
	}

	public void setCreateId(String createId) {
		this.createId = createId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreateDate", nullable = false, length = 23)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "ModifyID", length = 20)
	public String getModifyId() {
		return this.modifyId;
	}

	public void setModifyId(String modifyId) {
		this.modifyId = modifyId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ModifyDate", length = 23)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userAccountByUserId")
	public Set<PersonalJourney> getPersonalJourneysForUserId() {
		return this.personalJourneysForUserId;
	}

	public void setPersonalJourneysForUserId(Set<PersonalJourney> personalJourneysForUserId) {
		this.personalJourneysForUserId = personalJourneysForUserId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userAccountByCreateId")
	public Set<PersonalJourney> getPersonalJourneysForCreateId() {
		return this.personalJourneysForCreateId;
	}

	public void setPersonalJourneysForCreateId(Set<PersonalJourney> personalJourneysForCreateId) {
		this.personalJourneysForCreateId = personalJourneysForCreateId;
	}
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userAccount")
	public Set<GroupJourneyDetail> getGroupJourneyDetails() {
		return this.groupJourneyDetails;
	}

	public void setGroupJourneyDetails(Set<GroupJourneyDetail> groupJourneyDetails) {
		this.groupJourneyDetails = groupJourneyDetails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userAccountByCreateId")
	public Set<Group> getGroupsForCreateId() {
		return this.groupsForCreateId;
	}

	public void setGroupsForCreateId(Set<Group> groupsForCreateId) {
		this.groupsForCreateId = groupsForCreateId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userAccount")
	public Set<UserInGroup> getUserInGroups() {
		return this.userInGroups;
	}

	public void setUserInGroups(Set<UserInGroup> userInGroups) {
		this.userInGroups = userInGroups;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userAccountByModifyId")
	public Set<Group> getGroupsForModifyId() {
		return this.groupsForModifyId;
	}

	public void setGroupsForModifyId(Set<Group> groupsForModifyId) {
		this.groupsForModifyId = groupsForModifyId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userAccountByCreateId")
	public Set<GroupJourney> getGroupJourneysForCreateId() {
		return this.groupJourneysForCreateId;
	}

	public void setGroupJourneysForCreateId(Set<GroupJourney> groupJourneysForCreateId) {
		this.groupJourneysForCreateId = groupJourneysForCreateId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userAccountByModifyId")
	public Set<GroupJourney> getGroupJourneysForModifyId() {
		return this.groupJourneysForModifyId;
	}

	public void setGroupJourneysForModifyId(Set<GroupJourney> groupJourneysForModifyId) {
		this.groupJourneysForModifyId = groupJourneysForModifyId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userAccountByUserId")
	public Set<PersonalJourney> getPersonalJourneysForUserId_1() {
		return this.personalJourneysForUserId_1;
	}

	public void setPersonalJourneysForUserId_1(Set<PersonalJourney> personalJourneysForUserId_1) {
		this.personalJourneysForUserId_1 = personalJourneysForUserId_1;
	}

	
//	Authority
	private Collection<GrantedAuthority> authorities;
	
	@Transient
	@Override
	public Collection<GrantedAuthority> getAuthorities() {
		// TODO Auto-generated method stub
		return authorities;
	}
	public void setAuthorities(Collection<GrantedAuthority> authorities) {
		this.authorities = authorities;
	}
	@Transient
	@Override
	public String getUsername() {
		// TODO Auto-generated method stub
		return userId;
	}
	@Transient
	@Override
	public boolean isAccountNonExpired() {
		// TODO Auto-generated method stub
		return true;
	}
	@Transient
	@Override
	public boolean isAccountNonLocked() {
		// TODO Auto-generated method stub
		return true;
	}
	@Transient
	@Override
	public boolean isCredentialsNonExpired() {
		// TODO Auto-generated method stub
		return true;
	}
	@Transient
	@Override
	public boolean isEnabled() {
		// TODO Auto-generated method stub
		return true;
	}

}
