// default package
// Generated 2017/11/4 �W�� 01:37:15 by Hibernate Tools 5.2.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GroupJourney generated by hbm2java
 */
@Entity
@Table(name = "GroupJourney", schema = "dbo", catalog = "RoadToAdventure")
public class GroupJourney implements java.io.Serializable {

	private Integer groupJourneyId;
	private int groupId;
	private String groupJourneyName;
	private String groupJourneyContent;
	private String createId;
	private Date createDate;
	private String modifyId;
	private Date modifyTime;
	private Date beginDate;
	private Date endDate;
	private Set<GroupJourneyDetail> groupJourneyDetails = new HashSet<GroupJourneyDetail>(0);

	public GroupJourney() {
	}

	public GroupJourney(int groupId, String groupJourneyName, String createId, Date createDate) {
		this.groupId = groupId;
		this.groupJourneyName = groupJourneyName;
		this.createId = createId;
		this.createDate = createDate;
	}

	public GroupJourney(int groupId, String groupJourneyName, String groupJourneyContent, String createId,
			Date createDate, String modifyId, Date modifyTime, Date beginDate, Date endDate,
			Set<GroupJourneyDetail> groupJourneyDetails) {
		this.groupId = groupId;
		this.groupJourneyName = groupJourneyName;
		this.groupJourneyContent = groupJourneyContent;
		this.createId = createId;
		this.createDate = createDate;
		this.modifyId = modifyId;
		this.modifyTime = modifyTime;
		this.beginDate = beginDate;
		this.endDate = endDate;
		this.groupJourneyDetails = groupJourneyDetails;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "GroupJourneyID", unique = true, nullable = false)
	public Integer getGroupJourneyId() {
		return this.groupJourneyId;
	}

	public void setGroupJourneyId(Integer groupJourneyId) {
		this.groupJourneyId = groupJourneyId;
	}

	@Column(name = "GroupID", nullable = false)
	public int getGroupId() {
		return this.groupId;
	}

	public void setGroupId(int groupId) {
		this.groupId = groupId;
	}

	@Column(name = "GroupJourneyName", nullable = false, length = 50)
	public String getGroupJourneyName() {
		return this.groupJourneyName;
	}

	public void setGroupJourneyName(String groupJourneyName) {
		this.groupJourneyName = groupJourneyName;
	}

	@Column(name = "GroupJourneyContent")
	public String getGroupJourneyContent() {
		return this.groupJourneyContent;
	}

	public void setGroupJourneyContent(String groupJourneyContent) {
		this.groupJourneyContent = groupJourneyContent;
	}

	@Column(name = "CreateID", nullable = false, length = 20)
	public String getCreateId() {
		return this.createId;
	}

	public void setCreateId(String createId) {
		this.createId = createId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreateDate", nullable = false, length = 23)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "ModifyID", length = 20)
	public String getModifyId() {
		return this.modifyId;
	}

	public void setModifyId(String modifyId) {
		this.modifyId = modifyId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ModifyTime", length = 23)
	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "BeginDate", length = 23)
	public Date getBeginDate() {
		return this.beginDate;
	}

	public void setBeginDate(Date beginDate) {
		this.beginDate = beginDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EndDate", length = 23)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "groupJourney")
	public Set<GroupJourneyDetail> getGroupJourneyDetails() {
		return this.groupJourneyDetails;
	}

	public void setGroupJourneyDetails(Set<GroupJourneyDetail> groupJourneyDetails) {
		this.groupJourneyDetails = groupJourneyDetails;
	}

}
