// default package
// Generated 2017/11/4 �W�� 01:37:15 by Hibernate Tools 5.2.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * GroupJourneyDetailId generated by hbm2java
 */
@Embeddable
public class GroupJourneyDetailId implements java.io.Serializable {

	private int groupJourneyId;
	private int groupId;
	private Date createDate;

	public GroupJourneyDetailId() {
	}

	public GroupJourneyDetailId(int groupJourneyId, int groupId, Date createDate) {
		this.groupJourneyId = groupJourneyId;
		this.groupId = groupId;
		this.createDate = createDate;
	}

	@Column(name = "GroupJourneyID", nullable = false)
	public int getGroupJourneyId() {
		return this.groupJourneyId;
	}

	public void setGroupJourneyId(int groupJourneyId) {
		this.groupJourneyId = groupJourneyId;
	}

	@Column(name = "GroupID", nullable = false)
	public int getGroupId() {
		return this.groupId;
	}

	public void setGroupId(int groupId) {
		this.groupId = groupId;
	}

	@Column(name = "CreateDate", nullable = false, length = 23)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GroupJourneyDetailId))
			return false;
		GroupJourneyDetailId castOther = (GroupJourneyDetailId) other;

		return (this.getGroupJourneyId() == castOther.getGroupJourneyId())
				&& (this.getGroupId() == castOther.getGroupId())
				&& ((this.getCreateDate() == castOther.getCreateDate())
						|| (this.getCreateDate() != null && castOther.getCreateDate() != null
								&& this.getCreateDate().equals(castOther.getCreateDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getGroupJourneyId();
		result = 37 * result + this.getGroupId();
		result = 37 * result + (getCreateDate() == null ? 0 : this.getCreateDate().hashCode());
		return result;
	}

}
