// default package
// Generated 2017/11/4 �W�� 01:37:15 by Hibernate Tools 5.2.5.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GroupJourneyDetail generated by hbm2java
 */
@Entity
@Table(name = "GroupJourneyDetail", schema = "dbo", catalog = "RoadToAdventure")
public class GroupJourneyDetail implements java.io.Serializable {

	private GroupJourneyDetailId id;
	private GroupJourney groupJourney;
	private String latitude;
	private String longitude;
	private String createId;
	private String modifyId;
	private Date modifyDate;

	public GroupJourneyDetail() {
	}

	public GroupJourneyDetail(GroupJourneyDetailId id, GroupJourney groupJourney, String latitude, String longitude,
			String createId) {
		this.id = id;
		this.groupJourney = groupJourney;
		this.latitude = latitude;
		this.longitude = longitude;
		this.createId = createId;
	}

	public GroupJourneyDetail(GroupJourneyDetailId id, GroupJourney groupJourney, String latitude, String longitude,
			String createId, String modifyId, Date modifyDate) {
		this.id = id;
		this.groupJourney = groupJourney;
		this.latitude = latitude;
		this.longitude = longitude;
		this.createId = createId;
		this.modifyId = modifyId;
		this.modifyDate = modifyDate;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "groupJourneyId", column = @Column(name = "GroupJourneyID", nullable = false)),
			@AttributeOverride(name = "groupId", column = @Column(name = "GroupID", nullable = false)),
			@AttributeOverride(name = "createDate", column = @Column(name = "CreateDate", nullable = false, length = 23)) })
	public GroupJourneyDetailId getId() {
		return this.id;
	}

	public void setId(GroupJourneyDetailId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "GroupJourneyID", nullable = false, insertable = false, updatable = false)
	public GroupJourney getGroupJourney() {
		return this.groupJourney;
	}

	public void setGroupJourney(GroupJourney groupJourney) {
		this.groupJourney = groupJourney;
	}

	@Column(name = "Latitude", nullable = false, length = 30)
	public String getLatitude() {
		return this.latitude;
	}

	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

	@Column(name = "Longitude", nullable = false, length = 30)
	public String getLongitude() {
		return this.longitude;
	}

	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}

	@Column(name = "CreateID", nullable = false, length = 20)
	public String getCreateId() {
		return this.createId;
	}

	public void setCreateId(String createId) {
		this.createId = createId;
	}

	@Column(name = "ModifyID", length = 20)
	public String getModifyId() {
		return this.modifyId;
	}

	public void setModifyId(String modifyId) {
		this.modifyId = modifyId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ModifyDate", length = 23)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

}
